[package]
name = "su"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version="1.38.1",features = ["full"]}
nix = {version= "0.29.0",features=["user"]}

[profile.release]
lto=true
stripe=true